### ISSUE TITLE
javascript issue

### ISSUE THREAD

**Issue by alekkii** [ikushum/Django-Vue-Chat-App#2] opened 2020-04-15 07:18 UTC
l run the code and got a blank page at  /chat but the page title gets displayed

**Comment by ikushum** [comment] 2020-04-17 07:56
Hi @alekkii  It's been a long time since I wrote that code. But I think it's because there are no users. Try creating superuser using `python manage.py createsuperuser` command.

**Comment by rajeshrapally** [comment] 2020-04-22 19:24
I'm also getting black page when open /chat and I created superuser

**Comment by ikushum** [comment] 2020-04-23 11:17
@alekkii  @rajeshrapally

I think the issue is due to unavailability of a redis server.

We have channel layer that uses Redis as its backing store. To start a Redis server on port 6379, run the following command:

`docker run -p 6379:6379 -d redis:5`

Also make surel channels_redis is installed so that Channels knows how to interface with Redis. 

Please let me know if that helps :)

**Comment by ikushum** [comment] 2020-04-23 12:01
Hi @alekkii and  @rajeshrapally 

Please pull the new changes and hopefully the issue will be fixed. I've explicitly added versions for Vuetify.

Also make sure to start the redis server and create multiple users.

And finally please let me know if that solves your problem. :)

**Comment by rajeshrapally** [comment] 2020-04-23 17:48
> Hi @alekkii and @rajeshrapally
> 
> Please pull the new changes and hopefully the issue will be fixed. I've explicitly added versions for Vuetify.
> 
> Also make sure to start the redis server and create multiple users.
> 
> And finally please let me know if that solves your problem. :)



> Hi @alekkii and @rajeshrapally
> 
> Please pull the new changes and hopefully the issue will be fixed. I've explicitly added versions for Vuetify.
> 
> Also make sure to start the redis server and create multiple users.
> 
> And finally please let me know if that solves your problem. :)

hi @ikushum, issue resolved, Now its working well, thank you so much for your quick response

**Comment by ikushum** [comment] 2020-04-24 07:23
since @rajeshrapally has confirmed the problem is fixed, I'm closing this issue.

**Closed by ikushum** 2020-04-24 07:23 UTC

**Comment by alekkii** [comment] 2020-04-26 17:07
hello @rajeshrapally thank you so much the issue is now resolved you such a
great guy. Keep up
the good work.
